# Generated by Django 4.2 on 2023-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('mobile', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                # 'db_table': 'tblFarmer',
            },
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('mobile', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('skills', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                # 'db_table': 'tblLabour',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('mobile', models.TextField()),
                ('farmer', models.TextField()),
                ('work', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                # 'db_table': 'tblTask',
            },
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('taskid', models.TextField()),
                ('fname', models.TextField()),
                ('fmobile', models.TextField()),
                ('task', models.TextField()),
                ('lmobile', models.TextField()),
                ('lname', models.TextField()),
                ('lskills', models.TextField()),
                ('lstatus', models.TextField()),
                ('fstatus', models.TextField()),
            ],
            options={
                # 'db_table': 'tblWorkStatus',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('lmobile', models.TextField()),
                ('fmobile', models.TextField()),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('ratings', models.BigIntegerField()),
            ],
            options={
                # 'db_table': 'tblRatings',
                'unique_together': {('lmobile', 'fmobile')},
            },
        ),
    ]
